import type { PortfolioProfile } from "@/types/profile";

export const defaultProfile: PortfolioProfile = {
  id: "main",
  first_name: "Muhammad",
  last_name: "Hasnain",
  eyebrow: "Available for selected builds",
  roles: ["Full Stack Developer", "Next.js Specialist", "UI Experience Builder"],
  hero_description:
    "I design and build premium full-stack web experiences with calm layouts, elegant motion, authenticated dashboards, and clean content workflows.",
  about_heading: "Building interfaces that feel precise, calm, and credible.",
  about_body:
    "My work combines product structure, engineering discipline, and visual restraint. I care about the details that make a portfolio feel expensive: measured spacing, fast feedback, useful admin flows, sharp typography, and motion that supports the story.",
  profile_image_url: "/images/profile.png",
  email: "you@example.com",
  social_links: ["LinkedIn", "GitHub", "Email"],
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "Supabase",
    "PostgreSQL",
    "Tailwind CSS",
    "Framer Motion",
    "API Routes",
    "Server Actions",
    "Auth",
    "Storage",
    "Responsive UI",
  ],
  marquee_items: [
    "Full Stack Developer",
    "Next.js Apps",
    "React Interfaces",
    "TypeScript Code",
    "Supabase Auth",
    "Database Projects",
    "Admin Dashboards",
    "Project CRUD",
    "Image Uploads",
    "API Routes",
    "Server Actions",
    "Framer Motion",
    "Tailwind CSS",
    "Responsive UI",
    "Contact Forms",
    "Open To Work",
  ],
  updated_at: new Date("2026-01-01T00:00:00.000Z").toISOString(),
};
