import type { PortfolioProfile } from "@/types/profile";

export const defaultProfile: PortfolioProfile = {
  id: "main",
  first_name: "Muhammad",
  last_name: "Hasnain",
  eyebrow: "Available for Full Stack & AI/ML roles · Immediate",
  roles: [
    "Full Stack Developer (MERN & Django)",
    "AI/ML Enthusiast",
    "Python & FastAPI Engineer",
    "Founder of DevConnect",
  ],
  hero_description:
    "Full Stack Developer specializing in web development and AI/ML integration — MERN Stack, Django, Python, FastAPI, and GPT-powered products. Built Career Compass AI, DevConnect, and Agentic QA. Seeking Full Stack or AI/ML Developer roles.",
  about_heading: "Building production web platforms with AI/ML at the core.",
  about_body:
    "I am a BS Computer Software Engineering student at COMSATS University Islamabad, Vehari Campus (8th semester, CGPA 3.34/4.00), based in Lahore, Pakistan. I design and ship full-stack web applications — from FastAPI backends and PostgreSQL data models to React dashboards, JWT/RBAC auth, and OpenAI/Gemini integrations. Founder of DevConnect and creator of Agentic QA for chatbot accuracy evaluation.",
  profile_image_url: "/images/profile.jpg",
  email: "hasnain.devconnect@gmail.com",
  social_links: [
    "LinkedIn|https://www.linkedin.com/in/m-hasnain-b600b8327/",
    "GitHub|https://github.com/RaoHasnain-016",
    "Portfolio|https://www.hasnainofficial.codes/",
    "Email|mailto:hasnain.devconnect@gmail.com",
  ],
  skills: [
    "React.js",
    "Next.js",
    "Angular",
    "Tailwind CSS",
    "Node.js",
    "Express.js",
    "Nest.js",
    "Django",
    "FastAPI",
    "Python",
    "MongoDB",
    "PostgreSQL",
    "Supabase",
    "Firebase Firestore",
    "OpenAI API",
    "Gemini API",
    "Prompt Engineering",
    "Agentic QA",
    "JWT Authentication",
    "REST API Design",
    "RBAC",
    "Git",
    "GitHub",
    "Figma",
    "Vercel",
  ],
  marquee_items: [
    "React.js",
    "Next.js",
    "Django",
    "FastAPI",
    "Python",
    "MERN Stack",
    "PostgreSQL",
    "MongoDB",
    "Supabase",
    "OpenAI API",
    "Gemini API",
    "Agentic QA",
    "JWT Auth",
    "RBAC",
    "TypeScript",
    "Tailwind CSS",
    "Prompt Engineering",
    "LLM Evaluation",
    "Full Stack Developer",
    "AI/ML Integration",
  ],
  updated_at: new Date("2026-07-22T00:00:00.000Z").toISOString(),
};
