import type { PortfolioProfile } from "@/types/profile";

export const defaultProfile: PortfolioProfile = {
  id: "main",
  first_name: "Muhammad",
  last_name: "Hasnain",
  eyebrow: "MERN Full Stack Developer | AI Engineer | Founder",
  roles: ["Full Stack Developer (MERN)", "AI Engineer", "System Architecture Learner", "Founder of DevConnect"],
  hero_description:
    "Results-driven developer from Vehari, Pakistan, building scalable MERN applications, AI-powered SaaS tools, secure REST APIs, RBAC dashboards, and client-ready business systems with JavaScript, TypeScript, React, Node.js, MongoDB, and OpenAI integrations.",
  about_heading: "MERN developer building practical web apps, AI workflows, and business systems.",
  about_body:
    "I am a BS Computer Software Engineering student at COMSATS University Islamabad, Vehari Campus, and a results-driven developer focused on MERN applications, REST APIs, JWT authentication, RBAC dashboards, AI agents, prompt engineering, and polished responsive interfaces. I founded DevConnect and Career Compass AI, and I am available for remote, on-site, full-time, part-time, contract, internship, and entry-level full-stack roles.",
  profile_image_url: "/images/profile.png",
  email: "hasnain.devconnect@gmail.com",
  social_links: ["LinkedIn|https://linkedin.com/in/m-hasnain", "GitHub|https://github.com", "TikTok", "Facebook", "Instagram"],
  skills: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Tailwind CSS",
    "Node.js",
    "Express.js",
    "Nest.js",
    "MongoDB",
    "Firebase Firestore",
    "JWT Authentication",
    "REST API Design",
    "OpenAI API",
    "AI Agent Development",
    "Prompt Engineering",
    "Git",
    "GitHub",
    "Vercel",
    "Netlify",
  ],
  marquee_items: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Tailwind CSS",
    "Node.js",
    "Express.js",
    "Nest.js",
    "MongoDB",
    "Firebase Firestore",
    "JWT Authentication",
    "REST API Design",
    "OpenAI API",
    "AI Agent Development",
    "Prompt Engineering",
    "Git",
    "GitHub",
    "Vercel",
    "Netlify",
  ],
  updated_at: new Date("2026-01-01T00:00:00.000Z").toISOString(),
};
